### ISSUE TITLE
send login failed back to client?

### ISSUE THREAD

**Issue by CanadianJeff** [stamparm/hontel#1]
after each failed attempt I want to write back to the client
"Login incorrect"
where do I put this?

**Comment by stamparm** [comment]
Please take a look at: https://thinkincredible.intraway.com/2016/02/05/implementing-python-telnet-server-testing-development/. They are also using `TelnetHandler` from `telnetsrv`.

There you'll see:

```
def authCallback(self, username, password):
    if username != "admin" or password != "admin": #Security comes first
        self.writeresponse("Invalid username/password")
```

My guess is that you should put something similar into the `class HoneyTelnetHandler(TelnetHandler):` inside `hontel.py`

**Comment by CanadianJeff** [comment]
ok I set it too

```

    def authCallback(self, username, password):
        if username is not None and password is not None:
            self._log("AUTH", "{}:{}" .format(username, password))

        if not(username == AUTH_USERNAME and password == AUTH_PASSWORD):
            self.writeline("login incorrect")
            raise Exception("[x] wrong credentials ('{}':'{}')".format(username, password))
```

seems to get the job done just fine

**Comment by CanadianJeff** [comment]
I have updated your hontel into python 3 and os independant so it runs on windows as well as posix will fork soon
